### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by AshuGrover93** [hse-aml/competitive-data-science#12]
Whenever I try submitting the assignement I get the error: TypeError: argument of type 'NoneType' is not iterable in line 60 of grader.py

I think the code in line 58 should be `if response.status_code == 201: `  and not `if request.status_code == 201:`

Please check this Iam unable to submit my assignment due to this issue.
Attaching a screenshot.

![Capture](https://user-images.githubusercontent.com/44069711/55670011-5a9ea680-589c-11e9-863b-875a9292b04e.PNG)

**Comment by joaopcnogueira** [comment]
I have the same issue here. Did you solve it?

**Comment by AshuGrover93** [comment]
> I have the same issue here. Did you solve it?
> 
> EDIT: I just realize that I was incorrectly passing the STUDENT_EMAIL wrong. I fixed that and it worked.

Thanks a lot... I was doing the same mistake and would have never figured that out... I had been almost a month now. I missed a character in my email id as well. This error is so misleading.  Thanks a ton again... :)
