### ISSUE TITLE
KNN sanity check

### ISSUE THREAD

**Issue by fses91** [hse-aml/competitive-data-science#2]
I think there is an issue in the sanity check

```
test_knn_feats = NNF.predict(X_test[:50])

print ('Deviation from ground thruth features: %f' % np.abs(test_knn_feats - true_knn_feats_first50[44:45]).sum())
```

Shouldn't it be:
```
test_knn_feats = NNF.predict(X_test[44:45])

print ('Deviation from ground thruth features: %f' % np.abs(test_knn_feats - true_knn_feats_first50[44:45]).sum())
```
Because else we are comparing the wrong rows.

**Comment by DmitryUlyanov** [comment]
Hi, I guess it should be `[:50]` everywhere, I will check. Thanks!

**Comment by fses91** [comment]
Yes that sound even better, and there is also an error at the bottom because you are not initializing the Grader.

**Comment by aguschin** [comment]
Fixed, closing the issue.
