### ISSUE TITLE
Grader not instantiated

### ISSUE THREAD

**Issue by dobrevnikolay** [hse-aml/competitive-data-science#20]
In compute_KNN_features at the last cell of the notebook the grader is not instantiated consequently cannot submit.

This works:

![Annotation 2020-05-01 234000](https://user-images.githubusercontent.com/12647334/80843655-20214d80-8c05-11ea-885d-af51ad7ed0e4.png)

**Comment by dobrevnikolay** [comment]
https://github.com/hse-aml/competitive-data-science/pull/14 Fixes the issue, please merge

**Comment by aguschin** [comment]
Merged, thanks.
