### ISSUE TITLE
Missing data in `readonly`

### ISSUE THREAD

**Issue by alexander-myltsev** [hse-aml/competitive-data-science#5]
There is a line in https://github.com/zyunsg/Advanced-Machine-Learning/blob/master/course2/week1/assignments/PandasBasics.ipynb:

```python
DATA_FOLDER = '../readonly/final_project_data/'
```

Is the folder missing in the root?

**Comment by arnauq** [comment]
Hi there,
if anyone is facing the same problem, the data can be downloaded from 

https://www.kaggle.com/c/competitive-data-science-final-project/data

**Comment by mindlapse** [comment]
There is an invite link to join the competition in the PandasBasics.ipynb notebook.  This must be done before the data can be downloaded.

**Comment by aguschin** [comment]
Fixed.
