### ISSUE TITLE
These files are not in the readonly directory referred to in the pandas exercise notebook

### ISSUE THREAD

**Issue by sdcharle** [hse-aml/competitive-data-science#7]
sales_train.csv.gz items.csv item_categories.csv shops.csv

Seems the data is in this project, but I can't get it (perhaps b/c not 'invited')

https://www.kaggle.com/c/competitive-data-science-final-project

**Comment by blairly** [comment]
This is pretty annoying. The provided coursera environment is too slow, and the data files are currently not available on Github. This issue was raised several months ago. Bad show.

**Comment by dustyturner** [comment]
If yourself or anyone else is still having issues, you just need to click the link to join the above kaggle competition. Once joined you can just download a zip of the required files:

https://www.kaggle.com/t/1ea93815dca248e99221df42ebde3540

It is pretty well hidden in the PandasBasics.ipynb notebook so I appreciate the frustration!

**Comment by aguschin** [comment]
Csv files for competitions have been added to repository, closing this.
